export enum BusinessType {
  RETAIL = "retail",
  RESTAURANT = "restaurant",
  CAFE = "cafe",
  BAR = "bar",
  GROCERY = "grocery",
  PHARMACY = "pharmacy",
  CLOTHING = "clothing",
  ELECTRONICS = "electronics",
  BEAUTY = "beauty",
  AUTOMOTIVE = "automotive",
  HARDWARE = "hardware",
  BOOKSTORE = "bookstore",
  SPORTS = "sports",
  JEWELRY = "jewelry",
  TOURISM = "tourism",
  MARKET_STALL = "market_stall",
  KAVA_BAR = "kava_bar",
  OTHER = "other"
}